os: linux
language: c
compiler: clang
jobs:
  include:
    - os: linux
      dist: xenial
      name: "X11 libraries"
      addons:
        apt:
          packages:
            - mesa-common-dev
            - libgl1-mesa-dev
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
    - os: osx
      name: "Cocoa libraries"
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
notifications:
  on_success: never
  on_failure: always
